### ISSUE TITLE
Able to omit binaryen installation

### ISSUE THREAD

**Issue by dmvolod** [acifani/setup-tinygo#5]
Sometimes, for example for compiling WebAssembly plugins with TinyGo `binaryen` installation is not needed.
It would be nice to have an option, to omit `binaryen` installation for reducing traffic and resource consumption

**Comment by acifani** [comment]
@dmvolod  Good point. I could try adding a boolean input like `install-binaryen`, which would default to `true`. What do you think?

**Comment by dmvolod** [comment]
Thank you, @acifani . It will be very good solution for all cases.

**Comment by acifani** [comment]
@dmvolod this should now be released in [v1.2.0](https://github.com/acifani/setup-tinygo/releases/tag/v1.2.0). Let me know if it works for you!

**Comment by dmvolod** [comment]
Thanks, a lot, @acifani 
CI works fine and faster right now
https://github.com/dmvolod/wasm-k8s-host-proxy/actions/runs/4567102751/jobs/8060475129?pr=3
